---
collections:
  - name: ansible.posix
    version: 1.5.1
  - name: ansible.netcommon
    version: 4.1.0
  - name: ansible.utils
    version: 2.9.0
  - name: cisco.ios
    version: 4.4.0
  - name: community.general
    version: 6.4.0
  - name: containers.podman
    version: 1.10.1
  - name: community.cip
    version: 1.0.1
  - name: https://github.com/redhat-cop/infra.osbuild.git
    type: git
    version: 2.0.0
